package com.cadergator10.advancedbasesecurity.common.tileentity;

import com.cadergator10.advancedbasesecurity.AdvBaseSecurity;
import com.cadergator10.advancedbasesecurity.common.globalsystems.DoorHandler;
import com.cadergator10.advancedbasesecurity.common.interfaces.IDevice;
import com.cadergator10.advancedbasesecurity.common.items.ItemDoorManager;
import net.minecraft.block.state.IBlockState;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.network.NetworkManager;
import net.minecraft.network.play.server.SPacketUpdateTileEntity;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

import java.util.UUID;

/**
 * The base used by most of the devices. Mainly readers and Door controllers.
 */
public class TileEntityDeviceBase extends TileEntity implements IDevice {
    UUID managerId = null; //manager
    UUID deviceId = UUID.randomUUID(); //device ID
    DoorHandler.Doors door = null; //the door.

    public NBTTagCompound pushMoretoUpdate(NBTTagCompound nbt){ //stuff to send to the client
        return nbt; //overridden by the other classes
    }
    @Override
    public NBTTagCompound getUpdateTag() { //get the data to send to client
        return pushMoretoUpdate(writeToNBT(super.getUpdateTag()));
    }
    @Override
    public SPacketUpdateTileEntity getUpdatePacket() { //get the packet to send to client.
        return new SPacketUpdateTileEntity(getPos(), 1, getUpdateTag());
    }
    @Override
    @SideOnly(Side.CLIENT)
    public void onDataPacket(NetworkManager net, SPacketUpdateTileEntity pkt) { //recieves packet from server
        readFromNBT(pkt.getNbtCompound());
    }

    @Override
    public void handleUpdateTag(NBTTagCompound tag) { //When update is recieved from server on client
        readFromNBT(tag);
    }

    @Override
    public boolean shouldRefresh(World world, BlockPos pos, IBlockState oldState, IBlockState newState) //whether it should refresh and send the data to client.
    {
        return (oldState.getBlock() != newState.getBlock());
    }

    @Override
    public void readFromNBT(NBTTagCompound nbt) {
        super.readFromNBT(nbt);
        if(nbt.hasUniqueId("deviceId"))
            this.deviceId = nbt.getUniqueId("deviceId");
        else
            this.deviceId = UUID.randomUUID();
        if(nbt.hasUniqueId("managerId"))
            this.managerId = nbt.getUniqueId("managerId");
        if(!nbt.hasKey("toclient") || !nbt.getBoolean("toclient")) {
            if (managerId != null)
                door = AdvBaseSecurity.instance.doorHandler.getDoorManager(managerId);
        }
    }

    @Override
    public NBTTagCompound writeToNBT(NBTTagCompound nbt) {
        super.writeToNBT(nbt);
        if(deviceId != null)
        nbt.setUniqueId("deviceId", this.deviceId);
        if(managerId != null)
            nbt.setUniqueId("managerId", this.managerId);
        return nbt;
    }

    @Override //on block first place, initiate TE
    public void newId() {
        deviceId = UUID.randomUUID();
        managerId = null;
        markDirty();
    }

    @Override
    public UUID getId() {
        return deviceId;
    }

    @Override
    public String getDevType() {
        return "default";
    }

    @Override
    public void setDoor(ItemStack heldItem) { //Set the door on this tileentity.
        ItemDoorManager.ManagerTag cardTag = new ItemDoorManager.ManagerTag(heldItem);
        if(cardTag.doorIDScan != null && cardTag.currentScanMode == 1) {
            AdvBaseSecurity.instance.logger.debug("Device " + getDevType() + " with deviceID " + deviceId + ": set managerId to " + cardTag.doorIDScan + " if exists");
            boolean found = AdvBaseSecurity.instance.doorHandler.SetDevID(deviceId, new DoorHandler.DoorIdentifier(cardTag.managerID, cardTag.doorIDScan), this.getDevType().equals("doorcontrol"));
            if(found){
                AdvBaseSecurity.instance.logger.debug("Device " + deviceId + " Found door! Linking...");
                managerId = cardTag.managerID;
                markDirty();
                door = AdvBaseSecurity.instance.doorHandler.getDoorManager(managerId);
            }
        }
    }

    @Override
    public void onPlace() { //when first placed do stuff. Autogen as this is done on the classes that extend this.
        //autogenerated stub
    }

    @Override
    public DoorHandler.Doors getDoor() {
        return door;
    }
}
